#!/bin/bash

conda install --channel=conda-forge python=3.7 pip hdf5=1.12.0 notebook voila
export HDF5_DIR=/srv/conda/envs/notebook
echo $HDF5_DIR

pip install git+https://github.com/hdmf-dev/hdmf
pip install git+https://github.com/NeurodataWithoutBorders/pynwb
pip install git+https://github.com/NeurodataWithoutBorders/nwb-jupyter-widgets@brunton_brains
pip install jupyter_contrib_nbextensions
pip install joblib
pip install lazy_ops
pip install --no-deps ndx-events

pip install git+https://github.com/h5py/h5py
pip install --force-reinstall --no-binary=h5py

jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension